@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.guigs44.farmingforengineers.entity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
